file_path:

  kegg_cofactors: data/kegg/cofactors.csv

  all_rxn_dict: cache/data/all_rxn_dict2.json
  all_cpd_dict: cache/data/all_cpd_dict.json
  mypool: cache/data/MYPOOL_20221120.npy

  # dG
  dG_dict: cache/data/dG.json
  gibb_concentration: data/gibbs/concentrations.tab
  gibb_rxn_ph7_quantity: data/gibbs/kegg_reactions_CC_ph70_quantity.tsv

  # Yield
  yield_dir: data/theoretical_yield/
  host_sbml: data/theoretical_yield/iJO1366.xml

  # cache 
  data_dir: cache/data/
  result_dir: cache/result/
  checkpoint_dir: cache/checkpoint/
  log_dir: cache/log/

#----------------
init:
  gen: 30
  pop_size: 20
  NrMax: 20

#-----------------
# M00001
glycolysis:
  abundant: ['C00001', 'C00002', 'C00003', 'C00004', 'C00005', 'C00006', 'C00007', 'C00008', 'C00009', 'C00010', 'C00080']
  ob_substrate: C00267
  ob_product: C00022

vanillin:
  abundant: ['C00001', 'C00002', 'C00003', 'C00004', 'C00005', 'C00006', 'C00007', 'C00008', 'C00009', 'C00010', 'C00080']
  ob_substrate: C00082
  ob_product: C00755



